### ISSUE TITLE
v2 source files

### ISSUE THREAD

**Issue by TroniPM** [JeremyWildsmith/darkedenkit#1]
hello, do you own the v2 source files server/client or do you know where i can to find it?

**Comment by JeremyWildsmith** [comment]
I've just reverse engineered the asset file format and provided a tool to decompress / compress by looking at the compiled binary files. As far as server / client source code, I've never seen them. Sorry.

Thanks,

Jeremy Wildsmith

**Comment by TroniPM** [comment]
thanks anyway!
